---
title: "Appendix S1 - Supplementary Figure"
subtitle: "Sampbias, a method to evaluate geographic sampling bias in species distribution data"
author: "Alexander Zizka, Alexandre Antonelli, Daniele Silvestro"
output: rmarkdown::pdf_document
header-includes: |
    \usepackage{float}
    \renewcommand{\thefigure}{S1.\arabic{figure}}
---

\newpage{}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```

```{r, fig.height = 8, fig.cap="The example dataset of mammal occurrences from the island of Borneo, as downloaded from www.gbif.org (n = 6,262), and the geographic gazetters of main cities, roads, rivers and airports used for the sampbias analysis."}
#libraries
library(raster)
library(ggplot2)
library(magrittr)
library(sp)
library(dplyr)
library(viridis)

#load data
occ <-read.csv(system.file("extdata", "mammals_borneo.csv", package="sampbias"), sep = "\t") %>% 
  dplyr::select(latitude = decimalLatitude, longitude = decimalLongitude) %>% 
  mutate(type = "Mammal occurrence")

data(airports)
data(waterbodies)
data(cities)
data(roads)
data(landmass)

# prepare for plotting
airp <- airports %>% crop(SpatialPoints(occ[,2:1])) %>%  coordinates() %>%  data.frame() %>% mutate(type = "Airport")
cit <- cities %>% crop(SpatialPoints(occ[,2:1])) %>%  coordinates() %>%  data.frame() %>%  mutate(type = "City")
pts <- bind_rows(occ, cit, airp)


riv <- waterbodies %>% crop(SpatialPoints(occ[,2:1])) %>%  fortify() %>%  mutate(type = "River")
road <- roads %>% crop(SpatialPoints(occ[,2:1])) %>%  fortify() %>%  mutate(type = "Road")
lin <- bind_rows(riv, road)


lma <- landmass %>% crop(SpatialPoints(occ[,2:1])) %>%  fortify()

# plot
ggplot()+
  geom_polygon(data = lma,
               mapping = aes(x = long, y = lat, group = group), lwd = 0.5, col = "grey40", fill = "transparent")+
  geom_path(mapping = aes(x = long, y = .data$lat, group = .data$group, shape = type, color = type),
            data = lin)+
  geom_point(data = pts, mapping = aes(x = longitude, y = latitude, linetype = type, color = type), size = 3)+
  scale_color_viridis(discrete = TRUE)+
  xlab("Longitude")+
  ylab("Latitude")+
  coord_fixed()+
  theme_bw()+
  theme(
    legend.position = "bottom"
  )
```
